title: Nathan Harvey
logo: assets/img/headshot_circle.png
description: Digital/Print Designer, Marketer, Business Developer, Account Manager, and Jack of all Trades
#show_downloads: true
theme: jekyll-theme-minimal